import { lazy, Suspense, type ComponentType, type ReactNode } from 'react';
import type { LucideProps } from 'lucide-react';
import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Box,
  Braces,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  Clipboard,
  ClipboardPaste,
  Clock,
  Cloud,
  Command,
  Contrast,
  Copy,
  CopyPlus,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  FileJson,
  FileText,
  Filter,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Github,
  GraduationCap,
  Grid2x2,
  GripVertical,
  HardDrive,
  Hash,
  History,
  IdCard,
  Info,
  Keyboard,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  List,
  Mail,
  Megaphone,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  Package,
  Palette,
  PanelLeft,
  Pencil,
  Pin,
  PinOff,
  Pipette,
  Plus,
  Quote,
  Redo2,
  RefreshCw,
  Reply,
  RotateCcw,
  Rows3,
  Search,
  SearchX,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SquareDashed,
  Sun,
  SunMoon,
  Table,
  Tag,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  Users,
  Variable,
  WifiOff,
  X,
  Zap,
} from 'lucide-react';

/**
 * Static set used by the shell (bundled). Every other Lucide icon (box and tab icons chosen by the
 * user) is loaded on demand through DynamicIcon, which only fetches the icon actually needed.
 */
export const staticIcons = {
  'alert-triangle': TriangleAlert,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-down': ArrowDown,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  box: Box,
  braces: Braces,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-circle-2': CircleCheckBig,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  clipboard: Clipboard,
  'clipboard-paste': ClipboardPaste,
  clock: Clock,
  cloud: Cloud,
  command: Command,
  contrast: Contrast,
  copy: Copy,
  'copy-plus': CopyPlus,
  database: Database,
  download: Download,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  eye: Eye,
  'eye-off': EyeOff,
  'file-json': FileJson,
  'file-text': FileText,
  filter: Filter,
  folder: Folder,
  'folder-input': FolderInput,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'git-branch': GitBranch,
  github: Github,
  'graduation-cap': GraduationCap,
  'grid-2x2': Grid2x2,
  'grip-vertical': GripVertical,
  'hard-drive': HardDrive,
  hash: Hash,
  history: History,
  'id-card': IdCard,
  info: Info,
  keyboard: Keyboard,
  languages: Languages,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'life-buoy': LifeBuoy,
  list: List,
  mail: Mail,
  megaphone: Megaphone,
  menu: Menu,
  'message-square': MessageSquare,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  palette: Palette,
  'panel-left': PanelLeft,
  pencil: Pencil,
  pin: Pin,
  'pin-off': PinOff,
  pipette: Pipette,
  plus: Plus,
  quote: Quote,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  reply: Reply,
  'rotate-ccw': RotateCcw,
  'rows-3': Rows3,
  search: Search,
  'search-x': SearchX,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'square-dashed': SquareDashed,
  sun: Sun,
  'sun-moon': SunMoon,
  table: Table,
  tag: Tag,
  terminal: Terminal,
  'trash-2': Trash2,
  'undo-2': Undo2,
  upload: Upload,
  users: Users,
  variable: Variable,
  'wifi-off': WifiOff,
  x: X,
  zap: Zap,
} satisfies Record<string, ComponentType<LucideProps>>;

export type StaticIconName = keyof typeof staticIcons;

type DynamicIconProps = LucideProps & { name: string; fallback?: () => ReactNode };
const DynamicIcon = lazy(() => import('lucide-react/dynamic').then((m) => ({ default: m.DynamicIcon as unknown as ComponentType<DynamicIconProps> })));

export interface IconProps extends LucideProps {
  name: string;
  /** Icon used while a dynamic icon loads or when the name is unknown. */
  fallback?: StaticIconName;
}

export function Icon({ name, fallback = 'box', size = 16, ...rest }: IconProps) {
  const Static = (staticIcons as Record<string, ComponentType<LucideProps>>)[name];
  const props = { size, strokeWidth: 1.9, 'aria-hidden': true, focusable: false, ...rest } as LucideProps;
  if (Static) return <Static {...props} />;
  const Fallback = (staticIcons as Record<string, ComponentType<LucideProps>>)[fallback] ?? staticIcons.box;
  return (
    <Suspense fallback={<Fallback {...props} />}>
      <DynamicIcon name={name} fallback={() => <Fallback {...props} />} {...props} />
    </Suspense>
  );
}
